Feature/gazebo model
lsd-maddrive/eSAUL-project pull request #1
Opened 2021-03-08 10:10 UTC by adhelll

2021-03-11 18:07 UTC, KaiL4eK requested changes

2021-03-11 18:07 UTC, KaiL4eK commented on esaul_description/.vscode/launch.json
> +{
Папку `.vscode` надо игнорить - это относится к IDE и не должно попадать в репо

2021-03-11 18:07 UTC, KaiL4eK commented on esaul_description/CMakeLists.txt
> +add_library(${PROJECT_NAME} src/esaul_plugin.cpp)
Плагин назван как название пакета - надо отделить, чтобы он звался esaul_plugin

2021-03-11 18:07 UTC, KaiL4eK commented on esaul_description/launch/gmap.launch
> +  <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
Этот пакет надо пускать из лаунча модели

2021-03-11 18:07 UTC, KaiL4eK commented on esaul_description/launch/gmap.launch
> +<launch>
Этот и другие файлы уже не относятся к описанию - это основной функционал робота, лучше создать отдельный пакет и там размещать скрипты и остальное

2021-03-11 18:07 UTC, KaiL4eK commented on esaul_description/launch/lidar.launch
> +  <node pkg="tf" type="static_transform_publisher" name="base_link_to_laser"
Разве это не публикуется из модели?

2021-03-11 18:07 UTC, KaiL4eK commented on esaul_description/urdf/esaul.xacro
> +  <link name="lidar_link">
Стоит все таки разделить создание модели на файлы:
- файл основной модели
- файл модели с лидаром

Так исключается дублирование кода + проще организовывать код

2021-04-03 20:03 UTC, maryrosened commented on esaul_software/config/move_base/global_costmap_params.yaml
> +  robot_base_frame: base_link
я думаю, что тут необходимо поставить base_footprint вместо base_link

2021-04-03 20:03 UTC, maryrosened commented on esaul_software/config/move_base/local_costmap_params.yaml
> +  robot_base_frame: base_link
замечание относиться к дополнению по (global/local)_costmap_params.yaml

2021-04-03 20:03 UTC, maryrosened commented on esaul_software/urdf/lidar.xacro
> +  <xacro:property name="lidar_mass" value="0.1" />
интересное решение продублировать код из файла **esaul_description/urdf/wheel_track_esual.xacro**, надеюсь так и надо :) 
а какой в итоге запускается? из этого файла или того, что выше?

2021-04-03 20:36 UTC, adhelll commented on esaul_software/urdf/lidar.xacro
> +  <xacro:property name="lidar_mass" value="0.1" />
wheel_track_esual.xacro - старая модель, lidar.xacro используется для esaul.xacro

2021-04-03 20:37 UTC, adhelll commented on esaul_software/config/move_base/global_costmap_params.yaml
> +  robot_base_frame: base_link
уже везде сделано через base_link

2021-04-07 18:23 UTC, KaiL4eK approved these changes

2021-04-07 18:23 UTC, merged